apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-init-sql
  namespace: corp-ai
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE TABLE IF NOT EXISTS documents(
      id SERIAL PRIMARY KEY,
      doc_id TEXT NOT NULL,
      chunk_id INT NOT NULL,
      content TEXT NOT NULL,
      embedding vector(768),
      metadata JSONB
    );
    CREATE INDEX IF NOT EXISTS documents_embedding_idx
      ON documents USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
