name: CI-CD
on:
  push:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build agent image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/corp-agent:$(git rev-parse --short HEAD) -f app/Dockerfile .
          docker push ghcr.io/${{ github.repository }}/corp-agent:$(git rev-parse --short HEAD)
      - name: K8s deploy
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/ns.yaml
            k8s/secrets/corp-secrets.yaml
            k8s/ollama/deployment.yaml
            k8s/ollama/service.yaml
            k8s/litellm/deployment.yaml
            k8s/litellm/service.yaml
            k8s/tei/deployment.yaml
            k8s/tei/service.yaml
            k8s/pgvector/init-configmap.yaml
            k8s/pgvector/statefulset.yaml
            k8s/pgvector/service.yaml
            k8s/agent/deployment.yaml
            k8s/agent/service.yaml
            k8s/agent/networkpolicy.yaml
            k8s/rbac.yaml
          images: |
            ghcr.io/${{ github.repository }}/corp-agent:$(git rev-parse --short HEAD)
          namespace: corp-ai
